spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: todo_user
    password: todo_pass
  jpa:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
